/* Generated by Cython 0.29.14 */

#ifndef __PYX_HAVE__edgemaze
#define __PYX_HAVE__edgemaze

#include "Python.h"
struct Point;
typedef struct Point Point;
struct DistancePoint;
typedef struct DistancePoint DistancePoint;

/* "edgemaze.pyx":58
 * 
 * 
 * ctypedef public struct Point:             # <<<<<<<<<<<<<<
 *     int x
 *     int y
 */
struct Point {
  int x;
  int y;
};

/* "edgemaze.pyx":62
 *     int y
 * 
 * ctypedef public struct DistancePoint:             # <<<<<<<<<<<<<<
 *     int x
 *     int y
 */
struct DistancePoint {
  int x;
  int y;
  int distance;
  Point prev;
};

#ifndef __PYX_HAVE_API__edgemaze

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void set_distance(DistancePoint, __Pyx_memviewslice, int __pyx_skip_dispatch);
__PYX_EXTERN_C void set_direction(DistancePoint, __Pyx_memviewslice, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__edgemaze */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initedgemaze(void);
#else
PyMODINIT_FUNC PyInit_edgemaze(void);
#endif

#endif /* !__PYX_HAVE__edgemaze */
